version: '3'

services:
  web:
    labels:
      - traefik.enable=true
      # Serve nexcloud over http - insecure install
      - traefik.http.services.${PROJECT_NAME?PROJECT_NAME must be set.}-web.loadbalancer.server.port=80
      - traefik.http.routers.${PROJECT_NAME?PROJECT_NAME must be set.}-web.rule=Host(`$HOST`)
      - traefik.http.routers.$PROJECT_NAME-web.entrypoints=websecure

