version: '3'

services:
  db:
    image: postgres:alpine
    container_name: ${PROJECT_NAME}-db
    restart: always
    volumes:
      - ../datas/db:/var/lib/postgresql/data:z
    env_file:
      - db.env

  redis:
    image: redis:alpine
    container_name: ${PROJECT_NAME}-redis
    restart: always

  app:
    image: nextcloud:fpm-alpine
    container_name: ${PROJECT_NAME}-app
    restart: always
    volumes:
      - ../www/nextcloud:/var/www/html:z
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    build: ./web
    container_name: ${PROJECT_NAME}-web
    restart: always
    volumes:
      - ../www/nextcloud:/var/www/html:z,ro
    depends_on:
      - app

  cron:
    image: nextcloud:fpm-alpine
    container_name: ${PROJECT_NAME}-crono
    restart: always
    volumes:
      - ../www/nextcloud:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

